### ISSUE TITLE
Missing character difference

### ISSUE THREAD

**Issue by danvk** [danvk/github-syntax#17]
See [this PR](https://github.com/hammerlab/guacamole/pull/163/files#diff-10):
http://cl.ly/image/462g0y0b0142

github gets the character difference but this extension does not.

**Comment by ryan-williams** [comment]
[another example](https://github.com/bigdatagenomics/adam/pull/374/files#diff-ff25f5d5b36c5edf637e1e7d378a168dR20)

Before:

![before](http://f.cl.ly/items/2C1Y2W0G0w1G1e1U3201/Screen%20Shot%202014-09-10%20at%2012.16.46%20PM.png)

After:

![after](http://f.cl.ly/items/1p1O2E2w0C3p2w063b05/Screen%20Shot%202014-09-10%20at%2012.17.07%20PM.png)

**Comment by ryan-williams** [comment]
is this a dupe of #16 ?

**Comment by danvk** [comment]
No, this is a pure bug. github-syntax currently only adds character diffs when github does. #16 is proposing that we go beyond that where it would be useful.

**Comment by ryan-williams** [comment]
cool, makes sense

**Comment by danvk** [comment]
This should be fixed by 424b3b82b7dc0170d62681a382cbbd3ff9a87167, though I can't seem to find the original diff in this bug!

**Comment by ryan-williams** [comment]
go [here](https://github.com/bigdatagenomics/adam/pull/374/files#diff-ff25f5d5b36c5edf637e1e7d378a168dR20) and search for "ADAM2Vcf"

**Comment by ryan-williams** [comment]
hot

![](http://f.cl.ly/items/1p2v0l0K1P0B1U2g0d0w/Screen%20Shot%202014-09-10%20at%201.27.52%20PM.png)

**Comment by danvk** [comment]
Great!
